const backgrounds = {
  0: `${process.env.PUBLIC_URL}/img/0.jpg`,
  1: `${process.env.PUBLIC_URL}/img/1.jpg`,
  2: `${process.env.PUBLIC_URL}/img/2.jpg`,
  3: `${process.env.PUBLIC_URL}/img/3.jpg`,
  61: `${process.env.PUBLIC_URL}/img/61.jpg`,
  63: `${process.env.PUBLIC_URL}/img/63.jpg`,
  65: `${process.env.PUBLIC_URL}/img/65.jpg`,
  95: `${process.env.PUBLIC_URL}/img/95.jpg`,
  80: `${process.env.PUBLIC_URL}/img/61.jpg`,

  // 45: "Fog",
  // 48: "Rime Fog",
  // 51: "Drizzle Light",
  // 53: "Drizzle Moderate",
  // 55: "Drizzle Intense",
  // 56: "Freezing Drizzle Light",
  // 57: "Freezing Drizzle dense intensity",
  // 61: "Rain Slight",
  // 63: "Rain Moderate",
  // 65: "Rain Heavy",
  // 66: "Freezing Rain Light",
  // 67: "heavy intensity",
  // 71: "Snow Fall: Slight",
  // 73: "Snow Fall: Moderate",
  // 75: "Snow Fall: Heavy",
  // 77: "Snow Grains",
  // 80: "Rain: Slight",
  // 81: "Rain: Moderate",
  // 82: "Rain: Violant",
  // 85: "Snow: Slight",
  // 86: "Snow: Heavy",
  // 95: "Thunderstorm",
};

export default backgrounds;
